[required]
activity = "${defaultPrefix}help"
token = "NotARealToken.PleaseFillIn.WithRealToken"
# User IDs that are admins
admins = [1234567898765432]
# Values: RECOMMENDED, SINGLE
sharding = "SINGLE"
[required.database]
host = "localhost"
port = 5432
username = "postgres"
password = "myverystrongpassword"
database = "xf8bot"
# HIGHLY RECOMMENDED
enableEncryption = true
[notrequired]
# Not required
# Note: If you don't have a webhook for the log dump, leave the field as "" or remove it.
logDumpWebhook = "https://discordapp.com/api/webhooks/please/fillinwithwebhook"
